In [7]:
import pandas as pd
sales = pd.read_csv("E:/Users/vcvm2/Downloads/Airbnb+Data/Airbnb Data/Global+Electronics+Retailer/Sales.csv", encoding='latin1')

In [9]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [11]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [13]:
sales['order_date'] = pd.to_datetime(sales['Order Date'], errors='coerce')
sales['delivery_date'] = pd.to_datetime(sales['Delivery Date'], errors='coerce')

In [15]:
sales[['order_date', 'delivery_date']].dtypes

order_date       datetime64[ns]
delivery_date    datetime64[ns]
dtype: object

In [17]:
sales.isnull().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
order_date           0
delivery_date    49719
dtype: int64

In [19]:
sales = sales.drop(columns=['Order Date', 'Delivery Date'])

In [21]:
sales.isnull().sum()

Order Number         0
Line Item            0
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
order_date           0
delivery_date    49719
dtype: int64

In [23]:
sales['delivery_status'] = sales['delivery_date'].isnull().map({
    True: 'Not Delivered',
    False: 'Delivered'
})

In [25]:
sales['delivery_time'] = (sales['delivery_date'] - sales['order_date']).dt.days

In [27]:
sales.duplicated().sum()

0

In [29]:
sales[sales.duplicated()]

Empty DataFrame
Columns: [Order Number, Line Item, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code, order_date, delivery_date, delivery_status, delivery_time]
Index: []

In [31]:
sales.duplicated().sum()

0

In [33]:
sales = sales.drop_duplicates()

In [35]:
sales.duplicated().sum()

0

In [37]:
sales.duplicated().sum()

0

In [39]:
sales.dtypes

Order Number                int64
Line Item                   int64
CustomerKey                 int64
StoreKey                    int64
ProductKey                  int64
Quantity                    int64
Currency Code              object
order_date         datetime64[ns]
delivery_date      datetime64[ns]
delivery_status            object
delivery_time             float64
dtype: object

In [43]:
sales[sales['Quantity'] < 0]

Empty DataFrame
Columns: [Order Number, Line Item, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code, order_date, delivery_date, delivery_status, delivery_time]
Index: []

In [45]:
sales[sales['Quantity'] < 0]

Empty DataFrame
Columns: [Order Number, Line Item, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code, order_date, delivery_date, delivery_status, delivery_time]
Index: []

In [49]:
sales[['CustomerKey', 'ProductKey', 'Order Number']].isnull().sum()

CustomerKey     0
ProductKey      0
Order Number    0
dtype: int64

In [51]:
sales[['Order Number', 'Line Item']].duplicated().sum()

0

In [53]:
sales.columns = sales.columns.str.strip().str.lower().str.replace(' ', '_')

In [57]:
sales.tail()

,order_number,line_item,customerkey,storekey,productkey,quantity,currency_code,order_date,delivery_date,delivery_status,delivery_time
62879,2243030,1,1216913,43,632,3,USD,2021-02-20,NaT,Not Delivered,NaN
62880,2243031,1,511229,0,98,4,EUR,2021-02-20,2021-02-24,Delivered,4.0
62881,2243032,1,331277,0,1613,2,CAD,2021-02-20,2021-02-23,Delivered,3.0
62882,2243032,2,331277,0,1717,2,CAD,2021-02-20,2021-02-23,Delivered,3.0
62883,2243032,3,331277,0,464,7,CAD,2021-02-20,2021-02-23,Delivered,3.0

In [59]:
sales.to_excel("E:/Users/vcvm2/Downloads/Airbnb+Data/Airbnb Data/Global+Electronics+Retailer/cleaned_Sales.xlsx", index=False)